name: bagla_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.2
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_riverpod: ^2.5.1
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/mobile_logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/google_icon.png
    - assets/facebook_icon.png
    - assets/count_links.png
    - assets/follow_clicks.png
    - assets/use_for_free.png
    - assets/mobile_logo.png
